sudo: required
services:
  - docker

before_install:
  - docker build -t wshito/sec06-frontend -f ./sec06-frontend/Dockerfile.dev ./sec06-frontend/

script:
  - docker run -e CI=true wshito/sec06-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "udemy-grider"
  env: "UdemyGrider-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-615073444073"
  bucket_path: "udemy-grider"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
